### ISSUE TITLE
center_loss和region_loss的影响

### ISSUE THREAD

**Issue by YanShuang17** [wqtwjt1996/UHT#1]
作者您好，我认为在loss中加入center_loss和region_loss的想法挺新颖的，但paper中貌似没有讨论这两个loss对模型性能的影响，想问一下作者，和单纯使用reg_loss相比，增加center_loss和region_loss对模型性能改善有多少？是否可以分享一下相关的实验对比记录？

**Comment by wqtwjt1996** [comment]
你好 感谢你的回复 我当时没有涉及这方面的实验 但是加上这个对比的确是一个很好的ablation analysis
